=== tmillermillert/school/ser322/XmlExamplesSrc/xmlfiles/person.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT person (name, (address)+, (email)+)>
<!ELEMENT name (first, last)>
<!ELEMENT address (street, city, state, zip)>
<!ATTLIST address location (home | work) #IMPLIED>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email primary (true | false) #IMPLIED>

=== tmillermillert/school/ser322/XmlExamplesSrc/xmlfiles/persondtd.xml
<?xml version='1.0'?>
<!DOCTYPE person SYSTEM './xmlfiles/person.dtd'>
<person>
	<name>
		<first>Bob</first>  <last>Smith</last>
	</name>
	<address location="home">
		<street>123 East Elm</street>
		<city>Boston</city>
		<state>MA</state>
		<zip>23130</zip>
	</address>
	<address location="work">
	</address>
	<email primary="true">bob@yahoo.com</email>
	<email primary="false">hacker@yahoo.com</email>
</person>
